name: My auto tests

on: [push]

jobs:
  name-of-my-jobs:
    runs-on: ubuntu-latest
    name: Run my tests
    steps:
      - name: Pull source repository
        uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
